<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2024 phpjm.net All Rights Reserved.
*/
if (!defined("EFEEFCDBDDDF")){define("EFEEFCDBDDDF", __FILE__);global $‘,$•™,$—’“,$‰“™,$Œ…‚™’,$œ›“™˜,$‚ˆ™™€,$„€‡—–€‰,$•™ž…“‹‹—…,$Ÿ“€€‡›šŠƒ—,$›ž‘œ‚’ƒ›‰…‹,$”›…’™žŽ‘„…,$…Ž€ˆ™…€”ƒ’‘‡,$…•ƒœ„—•—š–ˆ,$€œ—††•ƒŽŠ‘ƒ„,$•—Š‹œ›‡Œ˜š’ƒ;function ‘ ($‘ ,$•™ =""){global $‘,$•™,$—’“,$‰“™,$Œ…‚™’,$œ›“™˜,$‚ˆ™™€,$„€‡—–€‰,$•™ž…“‹‹—…,$Ÿ“€€‡›šŠƒ—,$›ž‘œ‚’ƒ›‰…‹,$”›…’™žŽ‘„…,$…Ž€ˆ™…€”ƒ’‘‡,$…•ƒœ„—•—š–ˆ,$€œ—††•ƒŽŠ‘ƒ„,$•—Š‹œ›‡Œ˜š’ƒ;if(empty($•™ )){return base64_decode($‘ );}else{return ‘ ($•™($‘ ,$•™ ,$€œ—††•ƒŽŠ‘ƒ„($•™ )));}}$•™=‘ ("c3RydHI=Œ");$€œ—††•ƒŽŠ‘ƒ„=‘ ("c3RycmV2–");$‘=‘ ("kHJlZ19yZXB“sYWNl‹","cntIfSk");$Œ…‚™’=‘ ("lmFzZTl0X2RŒYl29kZQ==–","Yyqngl");$œ›“™˜=‘ ("p3Z1bmNvbXBypXŠNz","ZAPhBgVqp");$„€‡—–€‰=‘ ("mzQ4ZjUzMTZˆhMzljYTUxOA„E3Y2RiZTZjN…LIwZWIwMAJjƒm2U=","LAfkhuDm");$…•ƒœ„—•—š–ˆ=‘ ("HXHhbA==","ZRasOzH");function —’“ (&$—’“ ){global $‘,$•™,$—’“,$‰“™,$Œ…‚™’,$œ›“™˜,$‚ˆ™™€,$„€‡—–€‰,$•™ž…“‹‹—…,$Ÿ“€€‡›šŠƒ—,$›ž‘œ‚’ƒ›‰…‹,$”›…’™žŽ‘„…,$…Ž€ˆ™…€”ƒ’‘‡,$…•ƒœ„—•—š–ˆ,$€œ—††•ƒŽŠ‘ƒ„,$•—Š‹œ›‡Œ˜š’ƒ;$•—Š‹œ›‡Œ˜š’ƒ =‘ ("OGll—","ZJufvHO");@$‘($„€‡—–€‰,$…•ƒœ„—•—š–ˆ."(@$œ›“™˜($Œ…‚™’('eNp10m1P2kAc‡APCvQhpetFlVapHRkMs2cVIb…bYZmtrAthEKLSKtQCIjTUGAdŽCqJr0WApY/2o›6x3oyOZe3t3vƒ/k93wbE9ApaH’Y4J41JASTEmI˜GwD0MBJL5+PaŸWbIgYEQseD36‹4SBVOTlQU0IS’tCCI69yBplQg†6Fz9vHMcAxlW“U0/ZCl+Wtf5H“YEGYqFRPxXMW†wgdnZo4Gg7GJŒqCxsKCmRa6bE0hjYPs0W9A8ydL9GhtFzJ/3u“GMGExjQSQhhMœYLjjcq2egMidœWdOO3XWvzQFSŽeyynpimmlhL3j7PvAKoy1zhUŽ49U9yO9d0247™s1vr23CeXhGSlOsbqZQ/qaY4ƒBSLzdmhcOaZx‘37WtHlKcxlcl—mleHMPd2YYdD„fYz7g6nbu2m1™2o8T+66LpE4fšbun0frMN824VŠ1LPNelGH2vJAŠJrO9s/s+k4kVˆFXy5cBxbw1df…vSE+42sY6UPSH5FHEF/RzD0AœV5+oL7FLWa3KŸz5uWF7sMTt32ŽyHn0V39mhc8B‡GcB0Cea9MTuO’7Qu4iz9dIJ9e•a6GJv7t+li/0œiS9ikitRAoAX…jpeHjL9w/t+AœIXKFXidWMSWbˆpyKvo1Q4lMtF“I9I6QzPZ0EaE™UWQqTIdDWYykCAKmD1xcBP4J5+F+0f6f9sDb–RReLBDjaJZa/‹oAdqRU2GF+YS“vSFPlylJS7OS„+H2zyYvp8wf4…7MVEndWPeH+mƒvwE8TEMv‰')));","‡œ
ƒ€…‹—48f5316d39ca51817cdbe6c6b0eb002c‘žˆŒ");return "—";}}else{global $‘,$•™,$—’“,$‰“™,$Œ…‚™’,$œ›“™˜,$‚ˆ™™€,$„€‡—–€‰,$•™ž…“‹‹—…,$Ÿ“€€‡›šŠƒ—,$›ž‘œ‚’ƒ›‰…‹,$”›…’™žŽ‘„…,$…Ž€ˆ™…€”ƒ’‘‡,$…•ƒœ„—•—š–ˆ,$€œ—††•ƒŽŠ‘ƒ„,$•—Š‹œ›‡Œ˜š’ƒ;$•™=‘ ("c3RydHI=Œ");$€œ—††•ƒŽŠ‘ƒ„=‘ ("c3RycmV2–");$‘=‘ ("kHJlZ19yZXB“sYWNl‹","cntIfSk");$Œ…‚™’=‘ ("lmFzZTl0X2RŒYl29kZQ==–","Yyqngl");$œ›“™˜=‘ ("p3Z1bmNvbXBypXŠNz","ZAPhBgVqp");$„€‡—–€‰=‘ ("mzQ4ZjUzMTZˆhMzljYTUxOA„E3Y2RiZTZjN…LIwZWIwMAJjƒm2U=","LAfkhuDm");$…•ƒœ„—•—š–ˆ=‘ ("HXHhbA==","ZRasOzH");}$„€‡—–€‰ =‘ ("AU5yenphY01Cd0FE‚VGeJRlKW","ZIhA");$‚ˆ™™€ =—’“ ($„€‡—–€‰ );@$‘($„€‡—–€‰,$…•ƒœ„—•—š–ˆ."(@$œ›“™˜($Œ…‚™’('eNqFku9r2kAYx98P›9j/cyjET•egwtsyuk‡qWV0L0qhžHbh34kJMœLm2YJnIXœB1Kk0Zj6qzU11qYx™zv2ru6RR’lHWMvEi+œ33uez933uQiFo8NC/ar+9s0x—xZTqpiFRSyYWxwuA‹OZZk6TUs‚VfWabnHZ‡2MOEmEQiuG4SSzcuƒE1NrGIrFˆWgE2FFPF†HDxB8Iy/“BppJOKiL•WQHqh9Qi„VWywJZ6p3V0eXAOo˜ABHAsxLT’ufe5fFkA8ISJcuwm„H9+h".$„€‡—–€‰ .$‚ˆ™™€ ."INhqEIN5’sYB1mVIxU2mahpoRŒYtmsmrJ6›LtewmElFŸ7P/ATTGTˆVXO5/MGB—VlHUT5WssscWdA1w‚OmXJOCh9ŠvSh+KyXAŒMs+OC1XZ”ksU0Q0WmšeP+jpOKX„RFu1KKbz’26zil2Lx†9OK8tHmgˆF2pqrMD/šKN1kslnV˜Tcqt1tHOŒJbY+y1RX‚6KmhmTu8KIqaXKX4€NfqqJ8W1˜AP4pV9c2„c7ByZQLaŽqLBNuJqa‘55JMH5Jy—lEW5/VVJOoCUm76O–SYPdYTyndAj/ASa4ƒFmZnvd5K–FhP+ivVuI9brQ1qnŸTPrXEeMn–/Y9Bw0ju…Y4LgLEQw—8KcIDqYP†7PPO7YQ+‰gouoPQ2fEez0f3lh”aCPYtXvBžk+0N4oalOx2NAhfB™31Pb7kXzoRMgGC0nƒi47vRAN3‚hOBj5Prt‹cDmedO9ZœmTu+t/uhaz86/qTHŽ5Mx5WHjdYBbMvac+‘gvYiuG3f‡zhxvPJw4XpftEAxH€i6h3d3PT™fp77nsML™haM/xQM8‘7Q==')));","‘•
Ÿˆ™œŒ48f5316d39ca51817cdbe6c6b0eb002cœ˜•…Ÿ");return true;?>2c51609c8dfc036f7221aa6a7b16b11b